tag_to_name = {
    "undefined": "UNDEFINED",
    "person1": "bogdan_krasilnikov",
    "person2": "alexander_apakaev",
    "person3": "alina_dmitrieva",
    "person4": "alisa_baryakina",
    "person5": "alisa_belousova",
    "person6": "anastasiya_hutorskaya",
    "person7": "anastasiya_shishkina",
    "person8": "anastasiya_solovyova",
    "person9": "anastasiya_zhdanova",
    "person10": "andrey_odintsov",
    "person11": "anna_chezganova",
    "person12": "anna_kalinina",
    "person13": "anna_tselisheva",
    "person14": "asya_obraztsova",
    "person15": "danil_dolgorukov",
    "person16": "danil_isupov",
    "person17": "daria_bakunovets",
    "person18": "daria_ohotnikova",
    "person19": "daria_pogrebnikova",
    "person20": "denis_leuhin",
    "person21": "diana_mamylova",
    "person22": "dmitriy_antonyuk",
    "person23": "dmitriy_rybakov",
    "person24": "ekaterina_rubtsova",
    "person25": "elisey_karamyshev",
    "person26": "gleb_paybarshev",
    "person27": "grigoriy_poshnagov",
    "person28": "ignat_atyulov",
    "person29": "ilsaf_salyahov",
    "person30": "ilya_lezhnin",
    "person31": "kirill_borisov",
    "person32": "kirill_yashmetov",
    "person33": "konstantin_kalinin",
    "person34": "lera_makerova",
    "person35": "margarita_polushina",
    "person36": "maria_baranova",
    "person37": "maria_gnetkovskaya",
    "person38": "matvey_manahov",
    "person39": "maxim_ivanov",
    "person40": "maxim_nazarov",
    "person41": "maxim_romanov",
    "person42": "maxim_stolbov",
    "person43": "mikhail_kugelev",
    "person44": "mikhail_shelemetev",
    "person45": "milena_ivanova",
    "person46": "miroslav_actuganov",
    "person47": "nikolay_kozlov",
    "person48": "oksana_surinovich",
    "person49": "olga_shmalko",
    "person50": "pavel_kuznetsov",
    "person51": "polina_smirnova",
    "person52": "renat_arslanov",
    "person53": "sergey_stepanov",
    "person54": "stepan_gluharev",
    "person55": "tahir_safarov",
    "person56": "tatyana_uskova",
    "person57": "vlada_ryabina",
    "person58": "vladimir_fedoseev",
    "person59": "vladislav_kovalev",
    "person60": "vladislav_pogorelov",
    "person61": "yuliana_zhulitova",
    "person62": "zahar_timofeev",
}

google_cell_to_name = {
    "Актуганов Мирослав Александрович": "miroslav_actuganov",
    "Барякина Алиса Константиновна": "alisa_baryakina",
    "Глухарев Степан Викторович": "stepan_gluharev",
    "Иванова Милена Андреевна": "milena_ivanova",
    "Карамышев Елисей Александрович": "elisey_karamyshev",
    "Кугелев Михаил Григорьевич": "mikhail_kugelev",
    "Лежнин Илья Витальевич": "ilya_lezhnin",
    "Степанов Сергей Евгеньевич": "sergey_stepanov",
    "Шелеметев Михаил Евгеньевич": "mikhail_shelemetev",
    "Антонюк Дмитрий Викторович": "dmitriy_antonyuk",
    "Калинин Константин Олегович": "konstantin_kalinin",
    "Ковалев Владислав Витальевич": "vladislav_kovalev",
    "Погорелов Владислав Юрьевич": "vladislav_pogorelov",
    "Рыбаков Дмитрий Олегович": "dmitriy_rybakov",
    "Столбов Максим Алексеевич": "maxim_stolbov",
    "Яшметов Кирилл Романович": "kirill_yashmetov",
    "Белоусова Алиса Дмитриевна": "alisa_belousova",
    "Гнетковская Мария Андреевна": "maria_gnetkovskaya",
    "Жбанова Руслана Андреевна": "ruslana_zhbanova",
    "Жулитова Юлиана Юрьевна": "yuliana_zhulitova",
    "Козлов Николай Константинович": "nikolay_kozlov",
    "Кузнецов Павел Андреевич": "pavel_kuznetsov",
    "Мамылова Диана Константиновна": "diana_mamylova",
    "Погребникова Дарья Константиновна": "daria_pogrebnikova",
    "Жданова Анастасия Александровна": "anastasiya_zhdanova",
    "Рубцова Екатерина Сергеевна": "ekaterina_rubtsova",
    "Рябина Влада Алексеевна": "vlada_ryabina",
    "Суринович Оксана Евгеньевна": "oksana_surinovich",
    "Ускова Татьяна Юрьевна": "tatyana_uskova",
    "Хуторская Анастасия Андреевна": "anastasiya_hutorskaya",
    "Целищева Анна Сергеевна": "anna_tselisheva",
    "Шмалько Ольга Александровна": "olga_shmalko",
    "Баранова Мария Николаевна": "maria_baranova",
    "Смирнова Полина Сергеевна": "polina_smirnova",
    "Апакаев Александр Борисович": "alexander_apakaev",
    "Атюлов Игнат Васильевич": "ignat_atyulov",
    "Долгоруков Даниил Игоревич": "danil_dolgorukov",
    "Иванов Максим Андреевич": "maxim_ivanov",
    "Калинина Анна Дмитриевна": "anna_kalinina",
    "Красильников Богдан Ярославович": "bogdan_krasilnikov",
    "Назаров Максим Дмитриевич": "maxim_nazarov",
    "Саляхов Ильсаф Ильнурович": "ilsaf_salyahov",
    "Тимофеев Захар Георгиевич": "zahar_timofeev",
    "Федосеев Владимир Дмитриевич": "vladimir_fedoseev",
    "Чезганова Анна Павловна": "anna_chezganova",
    "Арсланов Ренат Русланович": "renat_arslanov",
    "Борисов Кирилл Александрович": "kirill_borisov",
    "Дмитриева Алина Андреевна": "alina_dmitrieva",
    "Исупов Даниил Сергеевич": "danil_isupov",
    "Леухин Денис Андреевич": "denis_leuhin",
    "Манахов Матвей Николаевич": "matvey_manahov",
    "Одинцов Андрей Дмитриевич": "andrey_odintsov",
    "Охотникова Дарья Сергеевна": "daria_ohotnikova",
    "Пайбаршев Глеб Романович": "gleb_paybarshev",
    "Пошнагов Григорий Игоревич": "grigoriy_poshnagov",
    "Сафаров Тахир Маратович": "tahir_safarov",
    "Бакуновец Дарья Максимовна": "daria_bakunovets",
    "Макерова Валерия Валерьевна": "lera_makerova",
    "Образцова Анастасия Олеговна": "asya_obraztsova",
    "Полушина Маргарита Васильевна": "margarita_polushina",
    "Романов Максим Александрович": "maxim_romanov",
    "Соловьева Анастасия Александровна": "anastasiya_solovyova",
    "Шишкина Анастасия Романовна": "anastasiya_shishkina",
}
